version: "2"
services:
  mongo:
    container_name: mongo
    restart: always
    image: tutum/mongodb:2.6
    environment:
      - MONGODB_USER=JustinCarly
      - MONGODB_DATABASE=explorerdb
      - MONGODB_PASS=dTMqgaPaea@$^bIxaG91#5
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  caddy:
    image: abiosoft/caddy:0.10.11
    restart: always
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
      - "./.caddy:/root/.caddy"
networks:
  default:
    external:
      name: service-tier