version: "3"
services:
  web:
    container_name: ${CONTAINER_NAME}
    restart: always
    build: .
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - WALLET_PORT=${WALLET_PORT}
      - CONTAINER_NAME=${CONTAINER_NAME}
    volumes:
      - "./coins/.shekel:/root/.shekel"
    deploy:
      resources:
        limits:
          cpus: '0.85'
          memory: 1.5G
        reservations:
          memory: 1G
          cpus: '0.5'  
networks:
  default:
    external:
      name: service-tier
