version: "3"
services:
  web:
    container_name: ${CONTAINER_NAME}
    restart: always
    build: .
    environment:
      - NODE_ENV=production
      - WORKING_PATH=${WORKING_PATH}
      - COIN=${COIN}
      - SYMBOL=${SYMBOL}
      - DAEMON_NAME=${DAEMON_NAME}  
      - CONF_FILE_NAME=${CONF_FILE_NAME}
      - THEME=${THEME}
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - WALLET_USER=${WALLET_USER}
      - WALLET_PASSWORD=${WALLET_PASSWORD}
      - WALLET_PORT=${WALLET_PORT}
      - WALLET_NODE_1=${WALLET_NODE_1}
      - WALLET_NODE_2=${WALLET_NODE_2}
      - BLOCKINDEX=${BLOCKINDEX}
      - BLOCKHASH=${BLOCKHASH}
      - TXHASH=${TXHASH}  
      - ADDRESS=${ADDRESS}
      - GENESIS_TX=${GENESIS_TX}
      - GENESIS_BLOCK=${GENESIS_BLOCK}
      - CONTAINER_NAME=${CONTAINER_NAME}
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME} 
    volumes:
      - "./coins/.shekel:/root/.shekel"
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: 1.5G
        reservations:
          memory: 1G
          cpus: '0.1'
  mongo:
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    image: mongo:3.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=JustinCarly
      - MONGO_INITDB_DATABASE=explorerdb
      - MONGO_INITDB_ROOT_PASSWORD=m23Sm48brJHPWwF9rd2lM0
    volumes:
      - ./data:/data/db  
networks:
  default:
    external:
      name: service-tier
