version: "2"
services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo:3.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_DATABASE=collection
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  caddy:
    image: abiosoft/caddy:0.10.11
    restart: always
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
      - "./.caddy:/root/.caddy"
networks:
  default:
    external:
      name: service-tier
