FROM ubuntu:16.04

RUN apt-get update && apt-get upgrade -y
RUN echo "Installing dependencies..."
RUN apt-get install -y build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool ncurses-dev unzip git python zlib1g-dev wget bsdmainutils automake \
 && apt-get autoremove -y


